restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm_scheduler.py"
cluster-status: "slurm_status.py"
cluster-config: "/raid/user2/kieser/Phages_Nestle/atlas/atlas/cluster/slurm/cluster_spec.yaml"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
